### ISSUE TITLE
ValueError: No such layer: res5a_branch2a

### ISSUE THREAD

**Issue by linwang6** [BiomedicalMachineLearning/Spacell#2]
Hi, thanks for this cool tool, but when I tried to use it, it gave error, se below:

python spacell_classification.py 
2020-07-04 18:00:49.875302: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-07-04 18:00:50.177694: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9b90294800 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-04 18:00:50.177712: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "spacell_classification.py", line 263, in <module>
    run_combine_model()
  File "spacell_classification.py", line 67, in run_combine_model
    parallel_model_combine, model_ = st_comb_nn((SIZE[0], SIZE[1], N_CHANNEL), (cm_shape,), len(class_list))
  File "/Users/LW/miniconda3/lib/python3.6/site-packages/SpaCell/model.py", line 224, in st_comb_nn
    stage_5_start = resnet_base.get_layer("res5a_branch2a")
  File "/Users/LW/miniconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 563, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: res5a_branch2a

Could you tell me how to fix it? Thanks in advance.

**Comment by linwang6** [comment]
Hi, could you please help to address this issue? Thanks!
